// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO2JI8e2aAWuIW4JwKZhGRUH-oyIHwwTI',
    appId: '1:21609641170:web:ee8b6765ca8bbfe5c2290b',
    messagingSenderId: '21609641170',
    projectId: 'diyet-93737',
    authDomain: 'diyet-93737.firebaseapp.com',
    storageBucket: 'diyet-93737.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyuqrA_uocbk6XAMQEDPBMpP_aSXnLBzE',
    appId: '1:21609641170:android:881b7e3b40c77d56c2290b',
    messagingSenderId: '21609641170',
    projectId: 'diyet-93737',
    storageBucket: 'diyet-93737.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG44J2kvXbV_LA5tQqwP9XOmM8xeiBgDI',
    appId: '1:21609641170:ios:2404139c2648e569c2290b',
    messagingSenderId: '21609641170',
    projectId: 'diyet-93737',
    storageBucket: 'diyet-93737.appspot.com',
    iosClientId: '21609641170-vf2qkiqnn687qqhliact4b878fa69m51.apps.googleusercontent.com',
    iosBundleId: 'com.example.diyet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG44J2kvXbV_LA5tQqwP9XOmM8xeiBgDI',
    appId: '1:21609641170:ios:15f26006e1c51399c2290b',
    messagingSenderId: '21609641170',
    projectId: 'diyet-93737',
    storageBucket: 'diyet-93737.appspot.com',
    iosClientId: '21609641170-k6rs7cpph43mfacnq4dkap7ghe2shmnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.diyet.RunnerTests',
  );
}
